export const FORM_PROJECT = 'FORM_PROJECT';
export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_PROJECT_FORM = 'VALIDATE_PROJECT_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';


export const TASKS_PROJECTS = 'TASKS_PROJECTS';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const STATE_TASK = 'STATE_TASK';
export const CURRENT_TASK = 'CURRENT_TASK';
export const EDIT_TASK = 'EDIT_TASK';
